fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    zypprepo: "git://github.com/deadpoint/puppet-zypprepo.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
  symlinks:
    php: "#{source_dir}"
